### ISSUE TITLE
Fatal Error with Symfony 5.3

### ISSUE THREAD

**Issue by mbabker** [liip/LiipTestFixturesBundle#112]
When testing with Symfony 5.3, getting the below fatal error:

```sh
Fatal error: Cannot make static method Symfony\Bundle\FrameworkBundle\Test\KernelTestCase::getContainer() non static in class Liip\TestFixturesBundle\Test\FixturesTrait
```

Realizing the trait is removed (and inherently the issue addressed) on the 2.x branch after #26, this is still a blocker for apps trying to upgrade beyond Symfony 5.2 without either a patch for 1.x or 2.0 being released.

**Comment by thewalkingcoder** [comment]
Same way with LiipFunctionnalTestBundle, PR is merge https://github.com/liip/LiipFunctionalTestBundle/pull/584

**Comment by thewalkingcoder** [comment]
in addition I think that a path is also necessary in version 1.x because for example I have just tried a transition from symfony 5.2 to 5.3 but having php 5.2.34 on production i can't migrate to liipTestBundle 2.x (because require "php": "^7.3 || ^8.0)

**Comment by alexislefebvre** [comment]
It should be fixed now: https://github.com/liip/LiipFunctionalTestBundle/pull/584#issuecomment-852085158

**Comment by alexislefebvre** [comment]
> in addition I think that a path is also necessary in version 1.x because for example I have just tried a transition from symfony 5.2 to 5.3 but having php 5.2.34 on production i can't migrate to liipTestBundle 2.x (because require "php": "^7.3 || ^8.0)

PHP 5.2 or 7.2? You should be able to use that release which require PHP 7.1: https://packagist.org/packages/liip/functional-test-bundle#3.3.0

**Comment by alexislefebvre** [comment]
> Realizing the trait is removed (and inherently the issue addressed) on the 2.x branch after #26, this is still a blocker for apps trying to upgrade beyond Symfony 5.2 without either a patch for 1.x or 2.0 being released.

I think there's not much to do before releasing the 2.0 as stable. It would be awesome if several users test it:

```bash
composer require --dev liip/test-fixtures-bundle:^2.0.0-alpha2
```

Then follow the instructions: https://github.com/liip/LiipTestFixturesBundle/blob/2.x/UPGRADE-2.0.md

**Comment by borodiliz** [comment]
@alexislefebvre I've just updated my application to `2.0.0-alpha2` + SF 5.3: After moving from `FixturesTrait` all works perfectly. I use both ODM and ORM. **BIG THANKS**

**Comment by thewalkingcoder** [comment]
> > Realizing the trait is removed (and inherently the issue addressed) on the 2.x branch after #26, this is still a blocker for apps trying to upgrade beyond Symfony 5.2 without either a patch for 1.x or 2.0 being released.
> 
> I think there's not much to do before releasing the 2.0 as stable. It would be awesome if several users test it:
> 
> ```shell
> composer require --dev liip/test-fixtures-bundle:^2.0.0-alpha2
> ```
> 
> Then follow the instructions: https://github.com/liip/LiipTestFixturesBundle/blob/2.x/UPGRADE-2.0.md

@alexislefebvre  Sorry for my mistake, i try to migrate symfony 5.2 to 5.3, but i can't migrate LiipTestsFixtureBundle to 2.x because require php 7.3 and my production server is php **7.2.34**

**Comment by alexislefebvre** [comment]
@thewalkingcoder no problem. PHP 7.2 is not [supported anymore](https://www.php.net/supported-versions.php) so I think we should not support it in this bundle, sorry.

However, to my surprise [Symfony 5.3 supports PHP 7.2](https://packagist.org/packages/symfony/symfony#v5.3.0), so we may allow it too. Feel free to open a PR for the 2.x branch, to reset the changes about 7.2 made in that PR: https://github.com/liip/LiipTestFixturesBundle/pull/108/files

**Comment by thewalkingcoder** [comment]
@alexislefebvre and i thinks symfony 5.4 (in november) support too php 7.2 to preserv semserv.

**Comment by Chris53897** [comment]
I migrated to ^2.0.0-alpha2. It worked for me.
I hope it will be fixed in 1.x. Because many projects depend on that version.

**Comment by alexislefebvre** [comment]
@Chris53897 right, feel free to submit a PR for the 1.x branch.

**Comment by alexislefebvre** [comment]
The issue with Symfony 5.3 on the 2.x branch is fixed.

**Comment by alexislefebvre** [comment]
@Chris53897 here is a new release for the 1.x branch: https://github.com/liip/LiipTestFixturesBundle/pull/139#issuecomment-881926491

**Comment by Chris53897** [comment]
Thank you
