### ISSUE TITLE
Purge mode truncate not possible with keep_database_and_schema true

### ISSUE THREAD

**Issue by grudda** [liip/LiipTestFixturesBundle#136]
### Preconditions
Version: 2.0.0-alpha4

### Steps to reproduce

1. configure `keep_database_and_schema = true`
2. set purge mode to truncate
```
$this->databaseTool = self::getContainer()->get(DatabaseToolCollection::class)->get();
$this->databaseTool->setPurgeMode(ORMPurger::PURGE_MODE_TRUNCATE);
```

### Expected result
1. On a mysql database, the foreign key check should be disabled, so that truncation of tables works without throwing an exception.

### Actual result
1. Truncation fails with
```
SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint ...
```

The reason I could figure out so far is the slightly changed logic in `disableForeignKeyChecksIfApplicable` where in version 1.* the condition was 
```
if (!$this->isMysql()) {
        return;
}
```
and in version 2.* it's 
```
if (!$this->isMysql() || !$this->connection->isConnected()) {
        return;
}
```

Unfortunately there is no connection yet, when the lib tries to truncate the tables because there was no sql executed for database and schema creation.

**Comment by alexislefebvre** [comment]
Thanks for the report. I added this in #110 but I don't remember what was the initial issue. Maybe we should check that the database exist, instead of checking the connection.

**Comment by grudda** [comment]
Sounds good. Thanks for approval.

**Comment by alexislefebvre** [comment]
I think that the issue was that the bundle tried to disable foreign keys before the connection to the database was created.

I reverted the change in #145, if the issue appear again, we should fin another way to avoid it.

Please try with the last release: https://github.com/liip/LiipTestFixturesBundle/releases/tag/2.0.0-beta3

**Comment by grudda** [comment]
> I think that the issue was that the bundle tried to disable foreign keys before the connection to the database was created.
> 
Exactly this was the case!

> I reverted the change in #145, if the issue appear again, we should fin another way to avoid it.
> 
:+1: 

> Please try with the last release: https://github.com/liip/LiipTestFixturesBundle/releases/tag/2.0.0-beta3
>
Works now perfectly. Many thanks for taking care.
