### ISSUE TITLE
Error: Class 'Doctrine\Common\Cache\ArrayCache' not found

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipTestFixturesBundle#140]
### Preconditions
1. Get last versions on 1.x or 2.x branch

### Steps to reproduce
1. Run CI

### Expected result
1. Tests pass

### Actual result
1. Error: `Error: Class 'Doctrine\Common\Cache\ArrayCache' not found`

See https://github.com/liip/LiipTestFixturesBundle/runs/2950368172

It blocks #139

**Comment by KDederichs** [comment]
Just for reference:
https://github.com/doctrine/DoctrinePHPCRBundle/issues/360

Since it’s comming from there

**Comment by alexislefebvre** [comment]
TODO: revert #143 once https://github.com/doctrine/DoctrinePHPCRBundle/issues/360 will be fixed
