### ISSUE TITLE
Error with DBAL 3

### ISSUE THREAD

**Issue by darthf1** [liip/LiipTestFixturesBundle#150]
Hi!

At the moment, there are no blockers anymore for DBAL 3. ORM and Migrations now also support DBAL 3 and this package has no dependency on a specific DBAL version.

When upgrading `doctrine/dbal` to `3.1.3` I get the following error:

```
Error: Call to undefined method Doctrine\DBAL\Driver\PDO\SQLite\Driver::getName()
/builds/GtzQhjMy/0/xxx/xxx/api/vendor/liip/test-fixtures-bundle/src/Services/DatabaseToolCollection.php:50
```

When I downgrade `doctrine/dbal` to `2.13.4` everything works as before.

https://github.com/doctrine/dbal/blob/3.1.x/UPGRADE.md#bc-break-doctrinedbaldrivergetname-removed
https://github.com/doctrine/dbal/blob/3.1.x/UPGRADE.md#deprecated-doctrinedbaldrivergetname

**Comment by alexislefebvre** [comment]
Thanks for the report, we may use class names instead, as suggested in the changelog: https://github.com/doctrine/dbal/blob/3.1.x/UPGRADE.md#deprecated-doctrinedbaldrivergetname

**Comment by gjuric** [comment]
It looks like this is not the only issue with DBAL 3 support, after switching to class names I am getting the following error:

    Doctrine\DBAL\Exception: Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getListDatabasesSQL' is not supported by platform.

I am using sqlite and `SqlitePlatform` does not have this method defined, so it looks like an issue with DBAL.

edit: The issue I am facing is that I am using Sentry bundle that wraps the original driver into `Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriverForV3`. In that case `ORMSqliteDatabaseTool` is not used, but `ORMDatabaseTool` which does not work with Sqlite.

edit2: It makes no sense to have Sentry enabled in the test env, so I've removed it and can confirm that this works, #152 should fix this issue.

**Comment by gjuric** [comment]
I also had to add a [check](https://github.com/liip/LiipTestFixturesBundle/pull/152/commits/f79ea4281b11456af236e806f67b9cd7d5aed0b0) that uses `fetchColumn()` or `fetchOne()` depending on the version of Doctrine being used.

**Comment by alexislefebvre** [comment]
Please try with the last release: https://github.com/liip/LiipTestFixturesBundle/releases/tag/2.1.0

**Comment by darthf1** [comment]
`2.1.0` fixes the issue for me.

Thank you @gjuric  and @alexislefebvre
