### ISSUE TITLE
[SF 5.3] Impossible to make functionnal test with SQLite: Operation 'AbstractPlatform::getListDatabasesSQL' is not supported by platform.

### ISSUE THREAD

**Issue by AlexandreGerault** [liip/LiipTestFixturesBundle#154]
### Preconditions

My dependencies on a fresh Symfony app are:
```json
"require": {
    "php": ">=7.4",
    "ext-ctype": "*",
    "ext-iconv": "*",
    "composer/package-versions-deprecated": "1.11.99.4",
    "doctrine/doctrine-bundle": "^2.4",
    "doctrine/doctrine-migrations-bundle": "^3.2",
    "doctrine/orm": "^2.10",
    "symfony/console": "5.3.*",
    "symfony/dotenv": "5.3.*",
    "symfony/flex": "^1.3.1",
    "symfony/framework-bundle": "5.3.*",
    "symfony/proxy-manager-bridge": "5.3.*",
    "symfony/runtime": "5.3.*",
    "symfony/yaml": "5.3.*"
},
"require-dev": {
    "dama/doctrine-test-bundle": "^6.6",
    "doctrine/doctrine-fixtures-bundle": "^3.4",
    "liip/test-fixtures-bundle": "^2.0.0",
    "phpunit/phpunit": "^9.5",
    "symfony/browser-kit": "5.3.*",
    "symfony/css-selector": "5.3.*",
    "symfony/maker-bundle": "^1.34",
    "symfony/phpunit-bridge": "^5.3"
},
```
1. PHP 7.4 & PHP 8
2. Symfony 5.3

### Steps to reproduce

1. Install a fresh symfony application
```
symfony new app
cd app
composer require --dev phpunit/phpunit symfony/test-pack
```
2. Create a WebTestCase in `app/tests/DummyFunctionnalTest.php`
3. Install Doctrine and the maker bundle
```
composer require symfony/orm-pack
composer require --dev symfony/maker-bundle
```
4. Set the `DATABASE_URL` in the `.env.test` file :
```
DATABASE_URL="sqlite:///%kernel.project_dir%/var/app.db"
```
5. Create an entity with the maker
6. Create a fixture that creates an entity
```php
class PostFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $post = new Post();

        $post->setTitle("Titre");
        $post->setContent("Contenu");
        $post->setCreatedAt(new DateTimeImmutable());

        $manager->persist($post);
        $manager->flush();
    }
}
```
7. Install LiipTestFixturesBundle: 
```
composer require --dev liip/test-fixtures-bundle:^2.0.0
```
8. Write a test :
```php
class DummyFunctionalTest extends WebTestCase
{
    protected KernelBrowser $client;
    private AbstractDatabaseTool $databaseTool;

    protected function setUp(): void
    {
        parent::setUp();

        $this->client = static::createClient();
        $this->databaseTool = $this->client->getContainer()->get(DatabaseToolCollection::class)->get();
    }

    public function testDummy(): void
    {
        $this->databaseTool->loadFixtures([PostFixtures::class]);

        $this->assertNotNull($this->client->getContainer()->get(PostRepository::class)->findAll());
    }
}
```
9. Run the tests

### Expected result

1. I expect the test to run and reach the assert statement

### Actual result
I got this error when I run tests:
```
./bin/phpunit
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Testing 
E                                                                   1 / 1 (100%)

Time: 00:00.100, Memory: 16.00 MB

There was 1 error:

1) App\Tests\DummyIntegrationTest::testDummy
Doctrine\DBAL\Exception: Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getListDatabasesSQL' is not supported by platform.

/app/vendor/doctrine/dbal/src/Exception.php:22
/app/vendor/doctrine/dbal/src/Platforms/AbstractPlatform.php:2749
/app/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:102
/app/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:163
/app/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:60
/app/tests/DummyFunctionalTest.php:27

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by AlexandreGerault** [comment]
I looked at the source code reported by the error stacktrace. The `AbstractPlatform::getListDatabaseSQL` is a function that is defined only for throwing an  Exception when it is not overriding by a child class. Looking at the SqlitePlatform child class, I found no definitions for `getListDatabaseSQL` thus it is normal for the code to throw an exception.

The code from `Doctrine\DBAL\Platforms\AbstractPlatform` throwing the error is:
```php
public function getListDatabasesSQL()
{
    throw Exception::notSupported(__METHOD__);
}
```
Called from the LiipTestFixturesBundle in the `Services/DatabaseTools/ORMDatabaseTool` class:
```php
protected function createDatabaseIfNotExists(): void
{
    $params = $this->connection->getParams();
    if (isset($params['master'])) {
        $params = $params['master'];
    }
    $dbName = $params['dbname'] ?? '';

    unset($params['dbname'], $params['url']);

    // Unset url to avoid issue:
    // “An exception occurred in driver: SQLSTATE[HY000] [1049] Unknown database 'test'”

    $tmpConnection = DriverManager::getConnection($params);
    $tmpConnection->connect();

    // The '->listDatabases' is the one that calls the AbstractPlatform::getListDatabasesSQL method
    if (!\in_array($dbName, $tmpConnection->getSchemaManager()->listDatabases(), true)) {
        $tmpConnection->getSchemaManager()->createDatabase($dbName);
    }

    $tmpConnection->close();
}
```

However I have no idea how I could solve that myself unfortunately

**Comment by AlexandreGerault** [comment]
As SQLite seems to work on unique database this should not be possible to list databases. Thus a way to handle it could be creating the database anyway in a Sqlite context, kinda like this (that works in this specific case):
```php
protected function createDatabaseIfNotExists(): void
{
    $params = $this->connection->getParams();
    if (isset($params['master'])) {
        $params = $params['master'];
    }
    $dbName = $params['dbname'] ?? '';

    unset($params['dbname'], $params['url']);

    // Unset url to avoid issue:
    // “An exception occurred in driver: SQLSTATE[HY000] [1049] Unknown database 'test'”

    $tmpConnection = DriverManager::getConnection($params);
    $tmpConnection->connect();
    
    $databases = $tmpConnection->getDatabasePlatform() instanceof SqlitePlatform
        ? ['']
        : $tmpConnection->getSchemaManager()->listDatabases();

    if (!\in_array($dbName, $databases, true)) {
        $tmpConnection->getSchemaManager()->createDatabase($dbName);
    }

    $tmpConnection->close();
}
```

EDIT: I ended testing it by forking the repo and it seems it does not break the actual tests suite

**Comment by alexislefebvre** [comment]
What versions of `liip/test-fixtures-bundle` and `doctrine/dbal` are used? The last version of `liip/test-fixtures-bundle` declares a conflict with `doctrine/dbal` to avoid this issue: https://github.com/liip/LiipTestFixturesBundle/pull/152#issuecomment-946974059

**Comment by AlexandreGerault** [comment]
Looking at `composer.lock` I have `doctrine/dbal` version 3.1.3 and `liip/test-fixtures-bundle` version 2.1.0

**Comment by alexislefebvre** [comment]
3.1.3 is the version that was used to run tests 2 days ago: https://github.com/liip/LiipTestFixturesBundle/runs/3951469875?check_suite_focus=true#step:8:141

Maybe it works because the tests don't use an URL for sqlite: https://github.com/liip/LiipTestFixturesBundle/blob/b607d23373329ef0cc69183acfd5173f13c43bb4/tests/AppConfigSqlite/config.yml#L3-L7

We can override `createDatabaseIfNotExists` in the `ORMSqliteDatabaseTool` class.

**Comment by AlexandreGerault** [comment]
If you think that's the way to go I can take time to submit a PR.

But what I don't get is how this `createDatabaseIfNotExists` is being called on a sqlite database. Indeed, when I searched for occurences of the `createDatabaseIfNotExists` I find it is used only in `ORMDatabaseTool::loadFixtures` method.

But this method is beeing overrided in the `ORMSqliteDatabaseTool` class and thus isn't calling the `createDatabaseIfNotExists` method :thinking: 

Also, I ran the SQLite tests with some dumping and it never reach the code in `createDatabaseIfNotExists`... Wonder why it then happens when using in Symfony

Edit: I'm really interested to understand the difference since it can means some working behavior isn't covered by tests... But I don't get why has the tests really looks like the one we write in a Symfony application (for an integration/functional test)

**Comment by alexislefebvre** [comment]
I added tests with SQLite and URL in #155

**Comment by alexislefebvre** [comment]
@AlexandreGerault `ORMSqliteDatabaseTool` extends `ORMDatabaseTool`, so `createDatabaseIfNotExists` is called.

**Comment by AlexandreGerault** [comment]
Yeah, I saw for this inheritance. But what I don't get is that the only place `createDatabaseIfNotExists` is called is in `ORMDatabaseTool::loadFixtures` which is overrided in `ORMSqliteDatabaseTool::loadFixtures`. And it this last method, no `createDatabaseIfNotExists` is called, is it?

**Comment by alexislefebvre** [comment]
Right, I missed that `loadFixtures()` was overridden for SQLite. (and I forgot we had so much duplicated code :sweat_smile:)

**Comment by alexislefebvre** [comment]
Please add this check before ` $this->databaseTool->loadFixtures([PostFixtures::class]);` in your test:

```php
$this->assertInstanceOf(
    \Liip\TestFixturesBundle\Services\DatabaseTools\ORMSqliteDatabaseTool::class,
    $this->databaseTool
);
```

We'll probably see that the bundle returns the ORM database tool instead of the specific SQLite one.

---

Could you please put the sources of your example on a GitHub repo? I followed the steps and it worked for me, I had to install `doctrine/data-fixtures` and `doctrine/doctrine-fixtures-bundle`. And I didn't find a Doctrine class that match with `extends Fixture`, so I extended `Doctrine\Common\DataFixtures\AbstractFixture` and registered the class as a fixture. I may have a configuration different from yours.

**Comment by AlexandreGerault** [comment]
Here is the basic sources to produce the error: https://github.com/AlexandreGerault/debug-liip-test-fixtures-bundle

Now I'll make another branch with your test (it's failing): https://github.com/AlexandreGerault/debug-liip-test-fixtures-bundle/tree/debug/add-instance-of-sqlite-tool

**Comment by alexislefebvre** [comment]
I put my test projet on GitHub, please try it:

```
git clone git@github.com:alexislefebvre/LiipTestFixturesBundle-issue-154.git
cd LiipTestFixturesBundle-issue-154/
composer install
vendor/bin/phpunit --testdox
```

I have no error on my local environment, it uses PHP 7.4, not 8.0, but I don't think it should cause issues.

**Comment by alexislefebvre** [comment]
I missed that your project use DAMADoctrineTestBundle, please try this: https://github.com/liip/LiipTestFixturesBundle/blob/2.x/doc/caveats.md#damadoctrinetestbundle

**Comment by AlexandreGerault** [comment]
To put in the `config/packages/test/framework.yaml` ?

EDIT: Now I'e just the error telling I've no table

**Comment by alexislefebvre** [comment]
I added a missing information on the doc, you have to create the database and schema before running your tests: https://github.com/liip/LiipTestFixturesBundle/blob/2.x/doc/configuration.md#configuration

**Comment by PapyDanone** [comment]
FYI I am having the same issue with: 
- `symfony/framework-bundle` 5.3.10
- `doctrine/dbal` 3.1.4
- `liip/test-fixtures-bundle` 2.1.0
- `liip/functional-test-bundle` 4.4.3



 Note that I'm _not_ using DAMADoctrineBundle but changing `keep_database_and_schema` to `true` + re-creating the SQLite database before running the tests fixed it 👍 

```yaml
liip_test_fixtures:
    cache_db:
        sqlite: 'Liip\TestFixturesBundle\Services\DatabaseBackup\SqliteDatabaseBackup'
    keep_database_and_schema: true
    cache_metadata: true
```

**Comment by iCodr8** [comment]
> As SQLite seems to work on unique database this should not be possible to list databases. Thus a way to handle it could be creating the database anyway in a Sqlite context, kinda like this (that works in this specific case):
> 
> ```
> protected function createDatabaseIfNotExists(): void
> {
>     $params = $this->connection->getParams();
>     if (isset($params['master'])) {
>         $params = $params['master'];
>     }
>     $dbName = $params['dbname'] ?? '';
> 
>     unset($params['dbname'], $params['url']);
> 
>     // Unset url to avoid issue:
>     // “An exception occurred in driver: SQLSTATE[HY000] [1049] Unknown database 'test'”
> 
>     $tmpConnection = DriverManager::getConnection($params);
>     $tmpConnection->connect();
>     
>     $databases = $tmpConnection->getDatabasePlatform() instanceof SqlitePlatform
>         ? ['']
>         : $tmpConnection->getSchemaManager()->listDatabases();
> 
>     if (!\in_array($dbName, $databases, true)) {
>         $tmpConnection->getSchemaManager()->createDatabase($dbName);
>     }
> 
>     $tmpConnection->close();
> }
> ```
> 
> EDIT: I ended testing it by forking the repo and it seems it does not break the actual tests suite

Fixed the problem for me.
I added this fix as Pull Request.

See: https://github.com/liip/LiipTestFixturesBundle/pull/163

**Comment by alexislefebvre** [comment]
@AlexandreGerault I was able to have another error message with your project by changing the doctrine config to this:

```yaml
doctrine:
    dbal:
        driver: pdo_sqlite
        url: "%kernel.cache_dir%/test.db"
```

(instead of [this config](https://github.com/AlexandreGerault/debug-liip-test-fixtures-bundle/blob/6c49b96b001bc90997ba71aa7492f2725cf23377/config/packages/test/doctrine.yaml))

Could you please test and see if it gives you different results?

**Comment by flohw** [comment]
Hi @alexislefebvre,

I encountered the same issue. I applied the patch provided in the close pr to make my tests work on my computer for now (but they fail in the CI due to this issue but this is normal at this point)

I tried the configuration you provide but ended in the same result.
Something to notice : `url` is defined with `env(resolve:DATABASE_URL)` and my `.env.test` contains `DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db`.

Here is my complete configuration in my `config/packags/test/doctrine.yaml`:
```yaml
doctrine:
  dbal:
    logging: false
    schema_filter: ~
    driver: pdo_sqlite
    url: null
  orm:
    dql:
      datetime_functions:
        Year:        DoctrineExtensions\Query\Sqlite\Year
```

And the configuration in my `config/packages/doctrine.yaml`:
```yaml
doctrine:
    dbal:
        # backtrace queries in profiler (increases memory usage per request)
        #profiling_collect_backtrace: '%kernel.debug%'
        server_version: '8'
        charset: utf8mb4
        url: '%env(resolve:DATABASE_URL)%'
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
# ... A lot of configuration related to the project
```

[EDIT]: here is may configuration of `config/test/liip_test_fixtures.yaml` just in case it's needed:
```yaml
liip_test_fixtures:
  cache_db:
    sqlite: Liip\TestFixturesBundle\Services\DatabaseBackup\SqliteDatabaseBackup
```

Tell me if you need more information or tests. I am working on the project every day and can provide quick feedback.

Thank you

**Comment by flohw** [comment]
Sorry, I missed some part of the configuration... Here is the right errors with right configuration.

Error (with PR patch applied, same previous error when patch not applied):
`InvalidArgumentException: Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped.`. But I think this is an expected error.

<details><summary>Stack trace</summary>
/symfony/server/vendor/liip/test-fixtures-bundle/src/Services/DatabaseBackup/SqliteDatabaseBackup.php:68
/symfony/server/vendor/liip/test-fixtures-bundle/src/Services/DatabaseBackup/SqliteDatabaseBackup.php:46
/symfony/server/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:124
/symfony/server/tests/Functional/WebTestCase.php:29
/symfony/server/vendor/phpunit/phpunit/src/Framework/TestResult.php:726
/symfony/server/vendor/phpunit/phpunit/src/Framework/TestSuite.php:678
/symfony/server/vendor/phpunit/phpunit/src/Framework/TestSuite.php:678
/symfony/server/vendor/phpunit/phpunit/src/Framework/TestSuite.php:678
/symfony/server/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:670
</details>

Note : as the project also have an Angular client, the Symfony app is in `/symfony/server` (in a docker container)

adding the configuration `doctrine.dbal.path: '%env(resolve:DATABASE_URL)%'` in my `config/test/doctrine.yaml` file create another error:
`PDOException: SQLSTATE[HY000] [14] unable to open database file`

<details><summary>Stack trace</summary>
/symfony/server/vendor/doctrine/dbal/src/Driver/PDO/SQLite/Driver.php:42
/symfony/server/vendor/doctrine/dbal/src/Connection.php:325
/symfony/server/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:162
/symfony/server/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:61
/symfony/server/tests/Functional/WebTestCase.php:29
/symfony/server/vendor/phpunit/phpunit/src/Framework/TestResult.php:726
/symfony/server/vendor/phpunit/phpunit/src/Framework/TestSuite.php:678
/symfony/server/vendor/phpunit/phpunit/src/Framework/TestSuite.php:678
/symfony/server/vendor/phpunit/phpunit/src/Framework/TestSuite.php:678
/symfony/server/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:670
</details>

Just in case here this is the content of our custom `WebTestCase`:
<details><summary>Functional\Tests\WebTestCase</summary>

```php
<?php

namespace Functional\Tests;

use Doctrine\Common\DataFixtures\ReferenceRepository;
use Factory\Tests\Administration\User\AdminUserFactory;
use Fixtures\Tests\Entity\Administration\User\AdminUserFixtures;
use Liip\TestFixturesBundle\Services\DatabaseToolCollection;
use Liip\TestFixturesBundle\Services\DatabaseTools\AbstractDatabaseTool;
use Symfony\Component\BrowserKit\Cookie;
use Zenstruck\Browser\KernelBrowser;
use Zenstruck\Browser\Response\JsonResponse;
use Zenstruck\Browser\Test\HasBrowser;
use Zenstruck\Foundry\Test\Factories;

class WebTestCase extends \Liip\FunctionalTestBundle\Test\WebTestCase
{
    use Factories;
    use HasBrowser;

    protected AbstractDatabaseTool $databaseTool;
    protected ReferenceRepository $fixtures;

    protected function setUp(): void
    {
        parent::setUp();
        $this->databaseTool = static::getContainer()->get(DatabaseToolCollection::class)->get();
        $this->databaseTool->loadFixtures([
            AdminUserFixtures::class,
        ]);
    }

    protected function loadFixtures(array $classNames): void
    {
        $this->fixtures = $this->databaseTool->loadFixtures($classNames, true)->getReferenceRepository();
    }

    protected function createAdminClient(): KernelBrowser
    {
        return $this->createAuthenticatedClient(AdminUserFactory::ADMIN_USERNAME, 'password');
    }

    protected function createAuthenticatedClient(string $username, string $password): KernelBrowser
    {
        $response = $this->browser()
            ->post('/api/login_check', [
                'body' => [
                    'username' => $username,
                    'password' => $password,
                ],
            ])
            ->assertJson()
            ->use(function (JsonResponse $response) use ($username, $password) {
                self::assertTrue($response->isSuccessful(), "Cannot login user with $username:$password");
                $response->search('token');
            })->response();

        $browser = $this->browser();
        $browser->cookies()->set(new Cookie('JWT', $response->json()['token']));

        return $browser;
    }
}
```
</details>

**Comment by bjalt** [comment]
It's not directly related to the minimal project configuration at the beginning of the ticket, but I found the cause for my project to be the [getsentry/sentry-symfony](https://github.com/getsentry/sentry-symfony) tracing to cause the exact same error message. Disabling the tracing fixed the issue.

**Comment by flohw** [comment]
@bjalt Hi

Could you elaborate a bit more? I can't find this tracing option and don't understand what it is.
Should the issue be reported on sentry repository?

Thank you

**Comment by bjalt** [comment]
@flohw This is only relevant if you have a dependency on `sentry/sentry-symfony`:

Sentry can collect performance information which include database performance. To do this they need to decorate the database abstraction, which seems to cause the issue. 
This is enabled by default and can be deactivated in the configuration:

```yaml
# config/packages/sentry.yaml
sentry:
    tracing:
        enabled: false
```

**Comment by AlexandreGerault** [comment]
> @AlexandreGerault I was able to have another error message with your project by changing the doctrine config to this:
> 
> ```yaml
> doctrine:
>     dbal:
>         driver: pdo_sqlite
>         url: "%kernel.cache_dir%/test.db"
> ```
> 
> (instead of [this config](https://github.com/AlexandreGerault/debug-liip-test-fixtures-bundle/blob/6c49b96b001bc90997ba71aa7492f2725cf23377/config/packages/test/doctrine.yaml))
> 
> Could you please test and see if it gives you different results?

As soon as I've free time this week-end I'll test

**Comment by flohw** [comment]
> @flohw This is only relevant if you have a dependency on `sentry/sentry-symfony`:

Which I use :wink: 

Your solution works for me too. I will keep an eye here to provide other information if needed et try to look on the sentry one for the same purpose.

Thanks

**Comment by alexislefebvre** [comment]
> @flohw This is only relevant if you have a dependency on `sentry/sentry-symfony`:
> 
> Sentry can collect performance information which include database performance. To do this they need to decorate the database abstraction, which seems to cause the issue. This is enabled by default and can be deactivated in the configuration:
> 
> ```yaml
> # config/packages/sentry.yaml
> sentry:
>     tracing:
>         enabled: false
> ```

That's a very nice finding! Sentry can be disabled only in the `test` environment:

```yaml
# config/packages/test/sentry.yaml
sentry:
    tracing:
        enabled: false
```

**Comment by darthf1** [comment]
Same issue, but with 
```
"doctrine/doctrine-bundle": "2.6.0",
```

```
Testing /home/www/app/tests/Functional/Infrastructure/Download

Doctrine\DBAL\Exception : Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getListDatabasesSQL' is not supported by platform.
 /home/www/app/vendor/doctrine/dbal/src/Exception.php:22
 /home/www/app/vendor/doctrine/dbal/src/Platforms/AbstractPlatform.php:3059
 /home/www/app/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php:115
 /home/www/app/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:163
 /home/www/app/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:60
 /home/www/app/tests/Functional/FixtureTestCase.php:37
 /home/www/app/tests/Functional/Infrastructure/Download/RequestDownloadBuilderTest.php:39
```

**Comment by 77web** [comment]
I'm having same issue now :(

I dig into code and found `$driverName` is `Doctrine\DBAL\Logging\Driver` not `Doctrine\DBAL\Driver\PDO\SQLite\Driver` here 👇 
https://github.com/liip/LiipTestFixturesBundle/blob/2.x/src/Services/DatabaseToolCollection.php#L50

doctrine/dbal 3.3.4
doctrine/orm 2.11.2
symfony/doctrine-bridge 6.0.6

---

edit:

It seems that `getDriverName()` in DatabaseTool is just a string 👇 
https://github.com/liip/LiipTestFixturesBundle/blob/2.x/src/Services/DatabaseTools/ORMSqliteDatabaseTool.php#L37-L40

Then can't we use DatabasePlatform not DriverName to resolve appropriate DatabaseTool here?

**Comment by alexislefebvre** [comment]
@darthf1 and @77web please tell if the solution in [this comment](https://github.com/liip/LiipTestFixturesBundle/issues/154#issuecomment-1036412140) doesn't work for you. Do you use a package that decorate the connection to the database?

**Comment by 77web** [comment]
@alexislefebvre no, I never use sentry.
I tried setting logging&profiling to false in dbal config, but nothing changed.

**Comment by darthf1** [comment]
> @darthf1 and @77web please tell if the solution in [this comment](https://github.com/liip/LiipTestFixturesBundle/issues/154#issuecomment-1036412140) doesn't work for you. Do you use a package that decorate the connection to the database?

Nope, sentry is disabled for me in the `dev` and `test` environment.

**Comment by 77web** [comment]
It seems that dbal silently started using their logging middleware by default? 🤔️

**Comment by 77web** [comment]
maybe doctrine/doctrine-bundle v2.6.0 is the cause:
https://github.com/doctrine/DoctrineBundle/releases/tag/2.6.0

> https://github.com/doctrine/DoctrineBundle/pull/1456 thanks to @l-vo

**Comment by stopfstedt** [comment]
encountering the described error after upgrading to doctrine-bundle v2.6.0 today, for the first time.
using version 2.1.1 of this bundle, running on PHP 8.1.

**Comment by 77web** [comment]
Temporarily solved my problem by downgrading doctrine/doctrine-bundle to 2.5.x.
But it will occur again in the near future :(

**Comment by alexislefebvre** [comment]
Maybe we can find a way to disable this middleware, if it can fix the issue.

**Comment by alexislefebvre** [comment]
I found one difference while using different versions of `doctrine/doctrine-bundle`, on this line: 

https://github.com/liip/LiipTestFixturesBundle/blob/90a963021ba3a031e3371eb6b1168c9c41dc6ea7/src/Services/DatabaseToolCollection.php#L50

With v2.6.0 it returns `Doctrine\DBAL\Logging\Driver`.
With v2.5.7 it returns `Doctrine\DBAL\Driver\PDO\MySQL\Driver`.

With 2.6.0, it won't find the item for SQLite in the following nice, so it returns the default configuration, and the `ORMSqliteDatabaseTool` is not used when it should have been.

We have to rewrite how the type of database is detected, because `Doctrine\DBAL\Logging\Driver` is hiding it.

**Comment by 77web** [comment]
@alexislefebvre 
yes, I mentioned it in comment yesterday 😅 

> It seems that getDriverName() in DatabaseTool is just a string 👇
> https://github.com/liip/LiipTestFixturesBundle/blob/2.x/src/Services/DatabaseTools/ORMSqliteDatabaseTool.php#L37-L40
> Then can't we use DatabasePlatform not DriverName to resolve appropriate DatabaseTool here?

I'm not familiar with PHPCR and MongoDBODM, so I thought why not use DatabasePlatform to distinguish db type...

**Comment by alexislefebvre** [comment]
I'm sorry I missed your comment.

I'm not familiar with how the driver is loaded, it's still black magic for me. Feel free to submit a PR if you have an idea.

**Comment by ndench** [comment]
It appears that DoctrineBundle 2.6.0 now injects middlewares all the time (https://github.com/doctrine/DoctrineBundle/pull/1472/files#diff-36d403fbfadb131317c08db172ddbb7844ce35323d45c6096043b97ed066b60a)? I stepped through the code and even though I have both `logging: false` and `profiling: false` in my `config/test/doctrine.yaml` it's still injecting the LoggingMiddleware.

I'm not sure that we need to rewrite how the database is detected as much as we need to figure out how to disable the middlewares in the test environment? From what I can see, there's no way to remove them. If a `MiddlewareInterface` exists it's auto tagged and auto injected.

**Comment by ndench** [comment]
Ok, I lied. After a bit more investigation I've found another way we can detect the type of database. Created PR #176 to fix it. If you're having this issue please install my fork and let me know if it works for you.

**Comment by alexislefebvre** [comment]
@ndench thanks, this PR was merged.

Please try the last release: https://github.com/liip/LiipTestFixturesBundle/releases/tag/2.3.0
