### ISSUE TITLE
Support for Symfony 6

### ISSUE THREAD

**Issue by Chris53897** [liip/LiipTestFixturesBundle#158]
**Is your feature request related to a problem? Please describe.**
I want to run my PhpUnittest run locally against Symfony 6.

**Describe the solution you'd like**
Support Symfony 6. Maybe this includes a change to Php 8 and a mayor release.
WDYT?

**Additional context**
I did a quick test yesterday. But there are a lot of errors. I will try to have a look at it if there are simple solutions for the problems.

**Comment by alexislefebvre** [comment]
Feel free to open a PR to allow Symfony 6 in `composer.json` and add a job for Symfony 6 here: https://github.com/liip/LiipTestFixturesBundle/blob/09138f129f52490582137d4c911d4afac66bc7e4/.github/workflows/tests.yml#L26-L29

> Support Symfony 6. Maybe this includes a change to Php 8 and a mayor release. WDYT?

The last major release was done 3 months ago, I would prefer not to publish another release so soon, unless we can't find any workaround. In theory, it's possible to allow Symfony 6 while still supporting PHP `^7.2 || ^8.0`.

**Comment by Chris53897** [comment]
Thanks for the fast response.
Symfony 6 has already features that needs Php 8. I am not sure if this needed in the usecase/scope of this bundle.

I will dig deeper in the code after i find some free time.

**Comment by alexislefebvre** [comment]
Could the bundle use polyfills to use the new features? https://packagist.org/packages/symfony/polyfill-php80?query=symfony%2Fpolyfill-php8

**Comment by Chris53897** [comment]
Maybe. But they just cover basic polyfills. Add another Bundle the return type changed to `static`. And who knows what will change in Symfony 6 in the future.
This is a big step for all bundle developers.

**Comment by alexislefebvre** [comment]
It looks like it works: https://github.com/liip/LiipTestFixturesBundle/pull/160

**Comment by Chris53897** [comment]
Sounds good. Can you please add 
*composer show* after composer install? Just to be sure that really symfony 6 components are installed.

Some symfony components are only available as beta2.

**Comment by alexislefebvre** [comment]
You were right, I added a "Show Composer dependencies" step and it installed some packages from Symfony 5.3: https://github.com/liip/LiipTestFixturesBundle/runs/4292550469?check_suite_focus=true

`symfony/flex` is not installed, it probably cause this conf to be ineffective: `composer config extra.symfony.require "${{ matrix.symfony-version }}"`.

---

Update: calling `composer remove --dev doctrine/phpcr-bundle doctrine/phpcr-odm` to early caused issues that are fixed now. Now the CI try to install Symfony 6 but it fails because some releases are not stable yet, it will be fixed in a few days.

**Comment by Chris53897** [comment]
I did some [changes](https://github.com/Chris53897/LiipTestFixturesBundle/commit/5460cff31ef1e7ca6d803987929ea88c94ded0cf) and get the tests working on my local pc.
For this local setup i fixed the version to "doctrine/annotations": "1.13", but on github actions tests this should not be necessary.

I just saw that there other dependencies ([example](https://github.com/doctrine/DoctrinePHPCRBundle/blob/master/composer.json#L48)) that do not yet allow symfony 6.

**Comment by alexislefebvre** [comment]
Yes, I removed PHPCR on the CI to avoid Composer errors: https://github.com/liip/LiipTestFixturesBundle/pull/160/commits/343e173060df4f8e57722d9f162cd7084cc48808

**Comment by alexislefebvre** [comment]
Please try the last release, it supports Symfony 6: https://github.com/liip/LiipTestFixturesBundle/releases/tag/2.2.0

**Comment by Chris53897** [comment]
@alexislefebvre Thanks
