### ISSUE TITLE
Relationships are empty during tests after loading the fixtures

### ISSUE THREAD

**Issue by CedCannes** [liip/LiipTestFixturesBundle#159]
### Preconditions
        "doctrine/doctrine-fixtures-bundle": "^3.4",
        "hautelook/alice-bundle": "^2.9",
        "liip/test-fixtures-bundle": "^2.1",

### Steps to reproduce
I prepared a [repo](https://github.com/CedCannes/sf_bug_collections_empty_during_tests_with_fixtures) to show all this
1.Create entities in OneToMany relationship (here Board and Lane)
2.Create yml files of fixtures with 1 Board that has 4 Lanes
3.Write a test that loads the fixtures and checks that there is a collection of 4 lanes in board

### Expected result
1. The board should have 4 lanes

### Actual result
1. Failed asserting that actual size 0 matches expected size 4. Collection $board->getLanes() is empty

**Comment by CedCannes** [comment]
I wonder if the problem does not come from https://github.com/theofidry/AliceDataFixtures :thinking:

**Comment by CedCannes** [comment]
Well I think I found it, theofidry/AliceDataFixtures loader.
While waiting for a correction I have clear the entity manager after loading the fixtures files and the tests pass normally.

`static::getContainer()->get('doctrine')->getManager()->clear();`

**Comment by alexislefebvre** [comment]
Moved to https://github.com/theofidry/AliceDataFixtures/issues/185.
