### ISSUE TITLE
Postgresql schemas are not deleted

### ISSUE THREAD

**Issue by OndrosI** [liip/LiipTestFixturesBundle#174]
Hello, 
when I run the tests with fixtures, everything goes fine for the first run. Then I want to run the tests again, but there is a problem with deleting the database. The data will be deleted, but the schemas will not be deleted, so when I run the tests, I get a message
`PDOException: SQLSTATE[42P06]: Duplicate schema: 7 ERROR:  schema "..." already exists`

I am trying run fixtures with `$this->databaseTool->withPurgeMode(true)->loadFixtures([...])` but with no effect

**Comment by alexislefebvre** [comment]
Hello,
does `$this->databaseTool->loadFixtures([...])` give the same result?

**Comment by OndrosI** [comment]
> Hello, does `$this->databaseTool->loadFixtures([...])` give the same result?

yes, same result. 
In 1.x.x version was no problem with that.

**Comment by alexislefebvre** [comment]
Can you please provide a reproducible example?

**Comment by OndrosI** [comment]
> Can you please provide a reproducible example?


This is setup() method:

```
protected AbstractDatabaseTool $databaseTool;

    public function setUp(): void
    {
        parent::setUp();

        $this->databaseTool = static::getContainer()->get(DatabaseToolCollection::class)->get();

        $this->databaseTool->withPurgeMode(true)->loadFixtures(
            [
                TestCategoryClassFixtures::class,
                TestIssueStateClassFixtures::class,
                TestTenantClassFixtures::class,
                TestResponsiblePersonClassFixtures::class,
                TestCategoryClassFixtures::class,
                TestIssueClassFixtures::class,
                TestResponsiblePersonIssueClassFixtures::class,
                TestBlockedEmailClassFixtures::class,
                ApplicationClassFixtures::class,
                PermissionClassFixtures::class,
                RolePermissionClassFixtures::class
            ]
        );
    }
```
as I wrote, when I run the tests for the first time, everything is fine, the next time I run it, I get the error that schema "..." already exists.

Screen from db client where schemas are there but without tables
![image](https://user-images.githubusercontent.com/40022797/161503908-560485f0-512f-424f-97a9-957a2bbf0a18.png)

**Comment by alexislefebvre** [comment]
The tables should be in “Views”.

**Comment by OndrosI** [comment]
I tried to reinstall package then add the configuration yaml again like this and it works perfect now :)
```
liip_test_fixtures:
    keep_database_and_schema: true
```
