### ISSUE TITLE
`AbstractDatabaseTool::getBackupService()` relies on deprecated method

### ISSUE THREAD

**Issue by mbabker** [liip/LiipTestFixturesBundle#184]
The `AbstractDatabaseTool::getBackupService()` method tries to build a backup service by identifying the database platform when the ORM is in use.  However, `Doctrine\DBAL\Platforms\AbstractPlatform::getName()` is deprecated in favor of identifying platforms based on their class names and `instanceof` checks.

This one isn't a straightforward replacement because the container parameter name that this code is trying to reference is built around the simple identifiers the `getName()` method was returning, so a new strategy for resolving the database backup service for the ORM is going to be needed (for simplicity sake, you can probably map `instanceof` checks to the names that the deprecated `getName()` method is using).

**Comment by alexislefebvre** [comment]
Please review this proposal:

- #255
