### ISSUE TITLE
Excessive memory consuption due to DatabaseToolCollection service

### ISSUE THREAD

**Issue by pdoreau** [liip/LiipTestFixturesBundle#195]
Memory consumption increases excessively because of DatabaseToolCollection not removed from memory.

### Preconditions

1. Symfony 5.4
2. PHP 8.0.3
3. liip/test-fixtures-bundle 2.4.0

### Steps to reproduce

1. Use a parent test class holding the databaseTools reference
2. Write of test classes extending this parent class in such a way that the following snippet (present in parent class) is called a lot of times : `$this->databaseTool = static::getContainer()->get(DatabaseToolCollection::class)->get();`. I suppose this where memory consuption accumulates.

### Expected result
1. Tests complete successfully

### Actual result
1. An out of memory error is dispalyed and tests stop : `Fatal error: Allowed memory size of 335544320 bytes exhausted (tried to allocate 20480 bytes) in /app/vendor/symfony/cache/Adapter/ApcuAdapter.php on line 64`

Using a simple `unset($this->databaseTools)` in the parent class' `tearDown` function seems to solve the issue but I'm not sure this is the correct way, or it could maybe be integrated into the bundle.

**Comment by alexislefebvre** [comment]
Thanks for the report.

It could be added to the documentation.

Inheritance was used in the version 1 of this bundle, tests had to extend `Liip\TestFixturesBundle\Test\FixturesTrait`, that's no the longer the case, so I don't know how to call `teadDown` automatically. Maybe a event or listener PHPUnit would work.

**Comment by alexislefebvre** [comment]
I added `tearDown` in #196. Does it fit your needs?

**Comment by pdoreau** [comment]
@alexislefebvre yes it does :+1:  Thank you
