### ISSUE TITLE
Schema public cannot be recreated

### ISSUE THREAD

**Issue by mutan** [liip/LiipTestFixturesBundle#203]
Hello!

### Preconditions
Symfony 6.1.3, liip/test-fixtures-bundle 2.4

### Steps to reproduce
I try to load fixture during test (Php Unit):
```
$executor = $this->databaseTool->loadFixtures([UserFixture::class]);
```

### Expected result
Tests passed successfully, schema public exists.

### Actual result
Schema public is dropped, and I see this error:
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  must be owner of schema public
```

Postgres logs at that moment:
```
2022-08-17 20:34:48.637 UTC [762] ERROR:  must be owner of schema public
2022-08-17 20:34:48.637 UTC [762] STATEMENT:  DROP SCHEMA public
```

So, database is purged successfully, but schema public cannot be recreated.
If I pass second parameter (`$append = true`) to  `loadFixtures`, there is no error (but next test would not be independent, of course).

**Comment by alexislefebvre** [comment]
Hello!

It looks like the database user can drop a schema but not recreate it, can you check that this user has full rights on the database?

Alternatively, you can try the `keep_database_and_schema: true` option to purge the tables without altering the schema: https://github.com/liip/LiipTestFixturesBundle/blob/2.x/doc/configuration.md

**Comment by mutan** [comment]
Thanx

User was owner of database, but not schema.

**Comment by mutan** [comment]
I ought to add some further explanations.

For an unknown reason Symfony/Doctrine try to recreate tables in non-"public" scheme.

So, if you face "must be owner of schema public" or "SQLSTATE[3F000]: Invalid schema name" errors, just set schema explicitly: `schema="public"`.

**Comment by alexislefebvre** [comment]
@mutan thanks for the information. Where do you put this conf?

**Comment by mutan** [comment]
> @mutan thanks for the information. Where do you put this conf?

In the Doctrine's XML Mapping file (User.orm.xml). But conf may be in Symfony's entity-file too (User.php)
