### ISSUE TITLE
UserPasswordHasherInterface injection in fixtures

### ISSUE THREAD

**Issue by kl3sk** [liip/LiipTestFixturesBundle#208]
I create a User fixture with a hashed password provided by Symfony.
When I test the fixture without `test` (aka. php bin/console doctrine:fixtures), It works
When I use a plain password without `__constructor` injection, it works

It doesn't work if I use this bundle with dependecy injection.

### Preconditions

1. Symfony 6.1
2. PHP 8.1

### Steps to reproduce

1. Create `User Fixture`

```php
namespace App\DataFixtures;

use App\Entity\User;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class UserFixture extends Fixture {

    public function __construct(private readonly UserPasswordHasherInterface $hasher) { }

    public function load(ObjectManager $manager)
    {
        $user = new User();
        $user->setEmail('user@test.com');
        $user->setIsVerified(true);

        $password = $this->hasher->hashPassword($user, '123456789');
        $user->setPassword($password);
        $user->setRoles(['ROLE_USER']);

        $this->setReference('user_user', $user);
        $manager->persist($user);

        $user = new User();
        $user->setEmail('admin@test.com');
        $user->setIsVerified(true);

        $password = $this->hasher->hashPassword($user, '123456789');
        $user->setPassword($password);
        $user->setRoles(['ROLE_ADMIN']);

        $this->setReference('admin_user', $user);
        $manager->persist($user);

        $manager->flush();
    }
}
```

3. Inject `UserPasswordHasherInterface` to create a hashed password
4. Create a simple test senario
```php
...
        $f = $this->databaseTool->loadFixtures([
            UserFixture::class,
        ])->getReferenceRepository();
...
```

### Expected result

1. Passed test
2. (without injection)
![image](https://user-images.githubusercontent.com/2953145/193532801-786c84fd-9be0-4f0a-a667-db56a6896cf1.png)

### Actual result

1.  (with injection)
![image](https://user-images.githubusercontent.com/2953145/193532883-0f96b6bb-87e2-4867-a80f-25d387f4dd70.png)

```bash
PHPUnit 9.5.25 #StandWithUkraine

Testing
E                                                                   1 / 1 (100%)

Time: 00:00.109, Memory: 16.00 MB

There was 1 error:

1) App\Tests\User\Kernel\UserTest::testCreateUser
ArgumentCountError: Too few arguments to function App\DataFixtures\UserFixture::__construct(), 0 passed in /app/var/cache/test/ContainerSEank8S/getDoctrine_Fixtures_LoaderService.php on line 22 and exactly 1 expected

/app/src/DataFixtures/UserFixture.php:13
/app/var/cache/test/ContainerSEank8S/getDoctrine_Fixtures_LoaderService.php:22
/app/var/cache/test/ContainerSEank8S/App_KernelTestContainer.php:120
/app/var/cache/test/ContainerSEank8S/getFixturesLoaderFactoryService.php:20
/app/var/cache/test/ContainerSEank8S/App_KernelTestContainer.php:120
/app/var/cache/test/ContainerSEank8S/getORMDatabaseToolService.php:20
/app/var/cache/test/ContainerSEank8S/App_KernelTestContainer.php:120
/app/var/cache/test/ContainerSEank8S/getDatabaseToolCollectionService.php:22
/app/var/cache/test/ContainerSEank8S/App_KernelTestContainer.php:120
/app/vendor/symfony/dependency-injection/Container.php:215
/app/vendor/symfony/dependency-injection/Container.php:197
/app/vendor/symfony/framework-bundle/Test/TestContainer.php:109
/app/tests/User/Kernel/UserTest.php:29

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
make: *** [Makefile:177: test] Error 2
```

**Comment by alexislefebvre** [comment]
I don't know how to help you with this fixture, sorry.

But you can use plaintext instead of encoding the passwords, your tests will be faster: https://symfony.com/doc/6.0/security/passwords.html#configuring-a-password-hasher (see the section with “In tests however, secure hashes are not important”).

**Comment by kl3sk** [comment]
Hello,

Yes I used plaintext for now, but may I `log` my user in with this method for fonctional tests ?

**Comment by alexislefebvre** [comment]
Since Symfony 5.1, you can log in an user easily: https://symfony.com/doc/5.4/testing.html#logging-in-users-authentication

Otherwise if you pass login + password through a form, it should work too.

**Comment by kl3sk** [comment]
Self answer:

As @alexislefebvre said, hashing password is less slower and is not needed, because there is no security reasons on tests.

To solve my problem.

I made separate fixtures for my `User`, one for my `test env` with no password hashing and one for my `dev env` with hashing.
Used the `FixtureGroupInterface` to load the right `User` when required.

If `security.yaml` [is configured properly](https://github.com/liip/LiipTestFixturesBundle/issues/208#issuecomment-1266261859) , `User` can be looged with plaintext password.


Thank you, I do not used tests enough to be fully aware of all details.

I continue leaning 😄 

Closing

**Comment by alexislefebvre** [comment]
Possible cause that could explain that the fixture are not loaded:
- the service is not autowired and/or has incorrect tags, try this: https://github.com/liip/LiipTestFixturesBundle/blob/9b8e29f7cc58bc59c30bd41f67da52da3a841818/tests/App/config.yml#L42-L48
- the fixture doesn't extend / implement the right class, check this: https://github.com/liip/LiipTestFixturesBundle/blob/19c9f4281bff0d5e3571de4ba71b66c85ba0b0c4/tests/App/DataFixtures/ORM/LoadUserData.php#L21

**Comment by kl3sk** [comment]
If I don't misunderstand it doesn't work:

`services.yaml`
```yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # Add these lines
    App\DataFixtures\:
         resource: '../src/DataFixtures/*'
         tags: ['doctrine.fixture.orm']
```

Also add missing `extends` and `implements`


Trace:

```bash
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.company' doesn't exist

/app/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:49
/app/vendor/doctrine/dbal/src/Connection.php:1818
/app/vendor/doctrine/dbal/src/Connection.php:1761
/app/vendor/doctrine/dbal/src/Connection.php:1137
/app/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php:161
/app/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:141
/app/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMDatabaseTool.php:125
/app/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/AbstractDatabaseTool.php:167
/app/tests/User/Kernel/KernelTestSetup.php:42
/app/tests/User/Kernel/KernelTestSetup.php:37

Caused by
Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.company' doesn't exist
```

**Comment by kl3sk** [comment]
@alexislefebvre 

After some tries it appears that hashing password could work.

I remove the `dama/doctrine-test-bundle` package because it look like have conflicts with this package.

Manually removing test cache and start tests.

All tests are green.

At least I test the environment (injected in the fixtures 😉) and hash for other than `test`

Edit: 
Extending from `Doctrine\Bundle\FixturesBundle\Fixture` looks enough because this class implement required interfaces.

**Comment by alexislefebvre** [comment]
Thanks for the feedback.

About DAMA, please see https://github.com/liip/LiipTestFixturesBundle/blob/2.x/doc/caveats.md

**Comment by kl3sk** [comment]
Yes, I already read this. But I want to repopulate my database automatically.

For now my project is not big enough to feel an impact. I will look to this bundle afterwards.

The main problem I face off, is the cache that I need to remove manually.

**Comment by alexislefebvre** [comment]
Internal tests of data fixtures with dependency injection have been removed in GH-200, I restored them in GH-209.
