### ISSUE TITLE
post and preFixtures or Reference returning self make it hard to use

### ISSUE THREAD

**Issue by magnetik** [liip/LiipTestFixturesBundle#21]
### Preconditions
Using this bundle 1.0 with FunctionalTestBundle 3.0

### Steps to reproduce
I've added the trait to a `BaseWebTestCase` defined in my project (that allows to create client crafter for my needs).

### Expected result

Due to the `return self` type hint, I cannot override the `preReferenceSave` (or `postReferenceSave` in a class extending by BaseWebTestCase.

### Actual result
The result of this method is never used, so they can be declared as void.

**Comment by alexislefebvre** [comment]
> The result of this method is never used, so they can be declared as void.

I agree, but I think that it would be a BC break.

I removed these buggy returns in #22.
