### ISSUE TITLE
chore: improve ci for symfony 4.4

### ISSUE THREAD

**Issue by Chris53897** [liip/LiipTestFixturesBundle#220]
### Is your feature request related to a problem? Please describe.

CI is failing for symfony 4.4 because of doctrine/annotations v2.

Symfony 4.4 is no longer LTS.
Is it an option to drop support of symfony 4.4?

Otherwise ci needs to be adjusted. But i do not know how.
composer should only be allowed doctrine/annotations v1 for 4.4.

### Describe alternatives you've considered

none

### Additional context

none

**Comment by alexislefebvre** [comment]
> Symfony 4.4 is no longer LTS. Is it an option to drop support of symfony 4.4?

Symfony 4.4 still receive security updates until November 2023: https://symfony.com/releases/4.4

We can still support it, there must be some legacy projects that still run Symfony 4.4, they can still use the last updates of this bundle.
