### ISSUE TITLE
Drop support of PHP 7.2 and 7.3?

### ISSUE THREAD

**Issue by Chris53897** [liip/LiipTestFixturesBundle#228]
### Is your feature request related to a problem? Please describe.

Like in https://github.com/liip/LiipFunctionalTestBundle/issues/625
https://packagist.org/packages/liip/test-fixtures-bundle/php-stats#2

Maybe symfony 4.4 too?

### Describe alternatives you've considered

...

### Additional context

...

**Comment by alexislefebvre** [comment]
>Drop support of PHP 7.2 and 7.3?

Yes :+1: 

> Maybe symfony 4.4 too?

[4.4](https://symfony.com/releases/4.4) will receive security updates until November 2023. We can keep compatibility for now, unless this requires too much work
