### ISSUE TITLE
Deprecated DBAL APIs still in use

### ISSUE THREAD

**Issue by mbabker** [liip/LiipTestFixturesBundle#238]
https://github.com/doctrine/dbal/pull/5948, included in the DBAL 3.7 release, adds runtime deprecation notices for a number of legacy DBAL APIs which were deprecated around the DBAL 2.11 release and look to be removed from 4.0.  There are probably more cases than this, but these two came up in my test suite run after upgrading today:

```sh
  858x: Doctrine\DBAL\Connection::query is deprecated, please use executeQuery() instead. (Connection.php:1974 called by ORMDatabaseTool.php:215, https://github.com/doctrine/dbal/pull/4163, package doctrine/dbal)
    ...

  858x: Doctrine\DBAL\Connection::query is deprecated, please use executeQuery() instead. (Connection.php:1974 called by ORMDatabaseTool.php:229, https://github.com/doctrine/dbal/pull/4163, package doctrine/dbal)
    ...
```

**Comment by alexislefebvre** [comment]
Thanks for the report.

Would you like to open a PR?
