### ISSUE TITLE
[RFC] Post Fixtures Database restore

### ISSUE THREAD

**Issue by magnetik** [liip/LiipTestFixturesBundle#27]
**Is your feature request related to a problem? Please describe.**
I'd like to load some redis data that are related to fixtures.
I need the reference repository because the redis keys depends on the ID that are loaded.

When using the sqlite backup, the code of the fixtures is not loaded, so I cannot load my redis data.

**Describe the solution you'd like**

1. Maybe having a `postRestore` method in each fixtures (with a `TestFixturesBundle` interface) that is called after restoring a backup?
2. Maybe having an event when each fixture file is loaded?

I think I prefer the 1. 

**Describe alternatives you've considered**
Sort of related to #21, I wanted to use the `postFixtureBackupRestore` method, but it only provides the `backupFilePath` (whereas the `preFixtureBackupRestore` provides the object manager & the reference repository). 
So maybe I can do something if the `referenceRepository` is provided in the `postFixturesBackupRestore` call.

**Comment by alexislefebvre** [comment]
> Maybe having an event when each fixture file is loaded?

I would prefer this option, I'm not fond of callback methods.

We may define events like in FOSUserBundle: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/8bb87890cbd872c870f7bd146922906f6e8ddf5c/FOSUserEvents.php#L26

**Comment by darthf1** [comment]
I'm looking for something similar. I have two use cases:
- After the fixtures have been loaded, I would like to populate my Elasticsearch index
- After the fixtures have been loaded, the ES index is auto populated via an event. I need to call a specific refresh on each Index so the documents are visible during the test.

Would it not be easiest to add a callback function in the `FixturesTrait` like you have for e.g. `postFixtureSetup` and `postReferenceSave`?

**Comment by alexislefebvre** [comment]
I'm trying to add events in #81. Once it will work, it will be easier to add events where we want.

**Comment by alexislefebvre** [comment]
@magnetik 

>  I need the reference repository because the redis keys depends on the ID that are loaded.

Could you inject it in a service or you need the instance of this repository?

**Comment by alexislefebvre** [comment]
It should be possible with #81, if not, it will be easy to add events now.
