### ISSUE TITLE
Invalid orm schema handling after migration from test bundle 1.x -> 3.x and multiple entity managers

### ISSUE THREAD

**Issue by scaytrase** [liip/LiipTestFixturesBundle#30]
We use postgres and manage our database schema with custom migrations, not with schema tool (schema:update)

We have two separate connections and EMs pointing (for tests for sure) to the same database (using different sets of tables)

For the 1.x branch database structure was only purged for SQLite DB driver, so we have no issues

https://github.com/liip/LiipFunctionalTestBundle/blob/45cac28b3fafeb75aebc58c4a2cf74dd1e093569/Test/WebTestCase.php#L403-L449

But after migrating to 3.x with fixtures bundle (and I confirmed 2.x had the same code) schema is updated forcibly either with drop/create or update schema tool.

https://github.com/liip/LiipFunctionalTestBundle/blob/7b4e40176c8a4fb359f28c27b1f71d33296a6aa9/src/Services/DatabaseTools/ORMDatabaseTool.php#L122-L132

https://github.com/liip/LiipTestFixturesBundle/blob/16000bbcb18d5a559b5c3655ca7a90c8df2ba357/src/Services/DatabaseTools/ORMDatabaseTool.php#L127-L138

Since we have two EMs and two connection we got a strange situation while loading all sets of fixtures for both:

first EM drops the whole database and restores only own metadatas. 
Same does the second

We result with non-consistent database setup where not all tables present, thus tests fail

**Comment by scaytrase** [comment]
I hope #15 will fix it. Will try and report

**Comment by scaytrase** [comment]
Yep, It helps

**Comment by alexislefebvre** [comment]
Please try last release: https://github.com/liip/LiipTestFixturesBundle/releases/tag/1.1.0

**Comment by scaytrase** [comment]
Looks good

**Comment by alexislefebvre** [comment]
Thanks for the tests!
