### ISSUE TITLE
ORMDatabaseTool#enableForeignKeyChecksIfApplicable() does not enable FOREIGN_KEY_CHECKS

### ISSUE THREAD

**Issue by dmitry-vinogradov** [liip/LiipTestFixturesBundle#39]
Due to typo in SQL statement in ORMDatabaseTool#enableForeignKeyChecksIfApplicable()  foreign key check remains deactivated

### Preconditions

1. Whenever you load fixtures (Alice or Doctrine) the foreign key check for current connection  remains deactivated.

### Steps to reproduce

1.  Load fixtures
2. Execute following $this->getContainer()->get('doctrine')->getManager()->getConnection()->fetchAll('SELECT @@GLOBAL.foreign_key_checks, @@SESSION.foreign_key_checks')

### Expected result

1. The value of @@GLOBAL.foreign_key_checks is 1
2. The value of @@SESSION.foreign_key_checks is 1

### Actual result

1. The value of @@GLOBAL.foreign_key_checks is 1
2. The value of @@SESSION.foreign_key_checks is 0

**Comment by alexislefebvre** [comment]
Thanks for reporting this issue!

It has been fixed in the last release: https://github.com/liip/LiipTestFixturesBundle/releases/tag/1.3.1
