### ISSUE TITLE
Disabling / Enabling foreign key checks does not respect previous settings

### ISSUE THREAD

**Issue by dmitry-vinogradov** [liip/LiipTestFixturesBundle#42]
If disabling of the foreign key checks was made in userland's code before calling loadFixtureFiles() the purging routine of the library enables it which leads to unexpected SQL errors.

### Preconditions

1. suppose to have fixtures defined in YAML files which require disabled foreign key checks for loading.

### Steps to reproduce

1. in your test disable foreign key checks before fixture loading.
2. call loadFixtureFiles() with $append = false (default)
3. Fixture cannot be loaded due to foreign key constraints - the foreign key checks is enabled just right after purging.

### Expected result

1. foreign key checks should be disabled

### Actual result

1. foreign key checks is enabled

Fix proposal: https://github.com/liip/LiipTestFixturesBundle/pull/41

**Comment by alexislefebvre** [comment]
Fixed in #41

**Comment by alexislefebvre** [comment]
It's available in the last release: https://github.com/liip/LiipTestFixturesBundle/releases/tag/1.3.2
