### ISSUE TITLE
Call to undefined method Doctrine\ODM\MongoDB\SchemaManager::createDatabases()

### ISSUE THREAD

**Issue by pelayo** [liip/LiipTestFixturesBundle#54]
Trying to load some ODM fixtures gives the title error.

### Preconditions
version 1.6.0 with mongodb-dom 2.0.3

### Steps to reproduce
        $this->loadFixtures([], false, 'default', 'doctrine_mongodb', false);

### Expected result
Happy fixtures loaded

### Actual result
No fixtures loaded and unhappy "Call to undefined method Doctrine\ODM\MongoDB\SchemaManager::createDatabases()" error.

**Comment by borodiliz** [comment]
Same here. Did you find any solution @pelayo ?

**Comment by alexislefebvre** [comment]
This may be a typo here:

https://github.com/liip/LiipTestFixturesBundle/blob/7cf7f7c06115262eda03d8c446aa9517f8ee8532/src/Services/DatabaseTools/MongoDBDatabaseTool.php#L45

Does `$sm->createDatabase();` work?

**Comment by borodiliz** [comment]
> This may be a typo here:
> 
> https://github.com/liip/LiipTestFixturesBundle/blob/7cf7f7c06115262eda03d8c446aa9517f8ee8532/src/Services/DatabaseTools/MongoDBDatabaseTool.php#L45
> 
> Does `$sm->createDatabase();` work?

@alexislefebvre Still not working working with `$sm->createDatabase(); `:
```
Error: Call to undefined method Doctrine\ODM\MongoDB\SchemaManager::createDatabase()
```

But commenting that line solves the problem. From [MongoDB ODM UPGRADE FROM 1.x to 2.0]( https://github.com/doctrine/mongodb-odm/blob/master/UPGRADE-2.0.md):

> The createDatabases and createDocumentDatabases methods have been removed from Doctrine\ODM\MongoDB\SchemaManager. Databases are created implicitly in MongoDB 3.0.


My environment:
```
liip/test-fixtures-bundle                1.7.0
doctrine/mongodb-odm                     2.0.5
```

Thanks for your time!
