### ISSUE TITLE
InvalidArgumentException : "App\Tests\DataFixtures\UserFixtures1" is not a registered fixture

### ISSUE THREAD

**Issue by klodoma** [liip/LiipTestFixturesBundle#57]
Hi, 

This is probably not a but, maybe a configuration issue or something similar. 
If the fixtures are not in use App\DataFixtures directory then I get the following error message:

```
InvalidArgumentException : "App\Tests\DataFixtures\UserFixtures1" is not a registered fixture
 D:\Projects\espos\repos\s55-demo\vendor\doctrine\data-fixtures\lib\Doctrine\Common\DataFixtures\Loader.php:135
 D:\Projects\espos\repos\s55-demo\vendor\liip\test-fixtures-bundle\src\Services\SymfonyFixturesLoaderWrapper.php:19
 D:\Projects\espos\repos\s55-demo\vendor\liip\test-fixtures-bundle\src\Services\FixturesLoaderFactory.php:44
 D:\Projects\espos\repos\s55-demo\vendor\liip\test-fixtures-bundle\src\Services\DatabaseTools\ORMSqliteDatabaseTool.php:75
 D:\Projects\espos\repos\s55-demo\vendor\liip\test-fixtures-bundle\src\Test\FixturesTrait.php:86
 D:\Projects\espos\repos\s55-demo\tests\Controller\SomeControllerTest.php:20
```

Any suggestion how to register **App\Tests\DataFixtures\UserFixtures1** as fixture?

**Comment by alexislefebvre** [comment]
Please share the code of your fixture.

What version of Symfony do you use ?

**Comment by klodoma** [comment]
> Please share the code of your fixture.
> 
> What version of Symfony do you use ?
> 
> Do you use autowiring of services? It can work for your case: [liip/LiipFunctionalTestBundle#504 (comment)](https://github.com/liip/LiipFunctionalTestBundle/issues/504#issuecomment-480640875)

I'm playing around with the symfony demo app, so it's Symfony 5. But with Symfony 4 I get the same issue. 
Have a look here for the test and fixture:
https://github.com/klodoma/symfony-demo/tree/master/tests/DataFixtures

I have the impression that the problem comes from the fact that the fixture is not found in /src/DataFixtures because with that it works.

**Comment by alexislefebvre** [comment]
Did the last comment helped you?

**Comment by klodoma** [comment]
I think so, as I didn't followed it up. Let's close this.
