### ISSUE TITLE
Upgrade doctrine/common to 3.0

### ISSUE THREAD

**Issue by bperel** [liip/LiipTestFixturesBundle#69]
`doctrine/common`, a dependency of this project, went out in late May in version 3.0. Would an upgrade create regressions or is it an easy thing to do?

Upgrading the dependency would be helpful since a lot of Doctrine and Symfony-related projects can use both `doctrine/common` 2.0 and 3.0 but the fact that liip/LiipTestFixturesBundle only supports version 2.0 prevents them from using the latest version.

**Comment by alexislefebvre** [comment]
Thanks for reporting this. I don't know if `doctrine/common` has breaking changes that will be not compatible with that bundle.

We can allow the version 3 in `composer.json`, open a PR and see if it installs version 3 and if it works.

**Comment by alexislefebvre** [comment]
Please see this comment: https://github.com/liip/LiipTestFixturesBundle/pull/72#issuecomment-707073507
