### ISSUE TITLE
Use interface injection instead of concrete class

### ISSUE THREAD

**Issue by williarin** [liip/LiipTestFixturesBundle#74]
https://github.com/liip/LiipTestFixturesBundle/blob/c8d4984f134e21c2b6e30b85dbd62e60fdf824dd/src/Services/DatabaseToolCollection.php#L35

In this file it would be better to use `Doctrine\Common\Annotations\Reader` interface instead of `Doctrine\Common\Annotations\AnnotationReader` concrete class, to allow custom decorated readers.

**Comment by alexislefebvre** [comment]
Thanks for the hint. Could you please open a PR with that change?

**Comment by alexislefebvre** [comment]
This has been changed, it(s in the last release: https://github.com/liip/LiipTestFixturesBundle/releases/tag/2.0.0-beta2
