### ISSUE TITLE
[2.0] Refactoring loadFixtures

### ISSUE THREAD

**Issue by Jean85** [liip/LiipTestFixturesBundle#87]
@lsmith77 raised the issued here: https://github.com/liip/LiipFunctionalTestBundle/pull/384#discussion_r165911900

Since a BC is allowed in the 2.0 release, it could be a good moment to refactor that method. The issue is that is really tangled! I wanted to take a stab at it but I don't know where to start... any suggestions? I'm not very familiar with that part, and I don't think it is well covered by tests..

**Comment by alexislefebvre** [comment]
Fixed in #26
