### ISSUE TITLE
Add GitHub Actions

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipTestFixturesBundle#90]
**Is your feature request related to a problem? Please describe.**
Travis CI changed the rules to use their CI: https://ropensci.org/technotes/2020/11/19/moving-away-travis/

**Describe the solution you'd like**
Add GitHub Actions 

**Describe alternatives you've considered**

**Additional context**
@lsmith77 please tell me if GitHub Actions is OK for Liip (for example, I hope Liip won't have to pay for the CI)

**Comment by lsmith77** [comment]
yeah .. lets move over to Github actions

**Comment by alexislefebvre** [comment]
Thanks for your answer.
